version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: smsworker:latest

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - ..:/home/app:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "172.18.0.4:sms.antyda.com"
